{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests26_31_3.py::test_range_of_given_arguments", "location": ["tests26_31_3.py", 4, "test_range_of_given_arguments"], "keywords": {"test_range_of_given_arguments": 1, "tests26_31_3.py": 1, "Folder_31": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00014331900092656724, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "342bb82c4393457093397f67905219ff", "node": "<WorkerController gw0>"}
{"nodeid": "tests26_31_3.py::test_nums", "location": ["tests26_31_3.py", 14, "test_nums"], "keywords": {"test_nums": 1, "tests26_31_3.py": 1, "Folder_31": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00011737999921024311, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "342bb82c4393457093397f67905219ff", "node": "<WorkerController gw1>"}
{"nodeid": "tests26_31_3.py::test_range_of_given_arguments", "location": ["tests26_31_3.py", 4, "test_range_of_given_arguments"], "keywords": {"test_range_of_given_arguments": 1, "tests26_31_3.py": 1, "Folder_31": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q26/command_results_3/Folder_31/generated_answer.py", "lineno": 2, "message": "TypeError: '>' not supported between instances of 'list' and 'int'"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_range_of_given_arguments():", "        initial_list = list(range(60, 97 + 1))", ">       assert sum_in_range(initial_list) == sum(initial_list)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q26/command_results_3/Folder_31/tests26_31_3.py", "lineno": 7, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def sum_in_range(nums):", ">       return sum(nums if (nums > 60 and nums <= 97) else 0)", "E       TypeError: '>' not supported between instances of 'list' and 'int'"], "reprfuncargs": {"args": [["nums", "[60, 61, 62, 63, 64, 65, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q26/command_results_3/Folder_31/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_range_of_given_arguments():", "        initial_list = list(range(60, 97 + 1))", ">       assert sum_in_range(initial_list) == sum(initial_list)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q26/command_results_3/Folder_31/tests26_31_3.py", "lineno": 7, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def sum_in_range(nums):", ">       return sum(nums if (nums > 60 and nums <= 97) else 0)", "E       TypeError: '>' not supported between instances of 'list' and 'int'"], "reprfuncargs": {"args": [["nums", "[60, 61, 62, 63, 64, 65, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q26/command_results_3/Folder_31/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q26/command_results_3/Folder_31/generated_answer.py", "lineno": 2, "message": "TypeError: '>' not supported between instances of 'list' and 'int'"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00014860800001770258, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "342bb82c4393457093397f67905219ff", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
